name: Deploy NGINX to Minikube with Helm

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Minikube
        shell: powershell
        run: |
          minikube start --driver=docker

      - name: Deploy with Helm
        shell: powershell
        run: |
          helm upgrade --install nginx charts/nginx
          kubectl rollout status deployment/nginx-service
