name: Build and Deploy Artifact

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Artifact Content
        run: |
          mkdir -p build
          echo "<h1>Deployed via GitHub Actions 🚀</h1>" > build/index.html
          zip -r nginx-artifact.zip build/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: nginx-artifact
          path: nginx-artifact.zip

  deploy:
    name: Deploy Artifact
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3.1.2
        with:
          name: nginx-artifact

      - name: Unzip and View Contents
        run: |
          unzip nginx-artifact.zip
          cat build/index.html
